insert into lienhe (Name_kh,Name_sp,Price,Address,Phone,Email,TieuDe,NoiDung) values ('sdaf','','','sadf','01676331802','trantungvinacom@gmail.com','sadf','sadf');
delete from lienhe where Id=2;
delete from lienhe where Id=3;
delete from lienhe where Id=4;
delete from lienhe where Id=5;
delete from lienhe where Id=6;
insert into lienhe (Name_kh,Name_sp,Price,Address,Phone,Email,TieuDe,NoiDung) values ('adsfđsa','','','sdaf','01676331802','trantungvinacom@gmail.com','ádf','sadf');
insert into lienhe (Name_kh,Name_sp,Price,Address,Phone,Email,TieuDe,NoiDung) values ('Trần Văn Tùng','Ainol Numy 3G Vegas','','Dông Abh','01676331802','tungtv.soict@gmail.com','Đặt hàng','liên hệ đặt hàng');
insert into lienhe (Name_kh,Name_sp,Price,Address,Phone,Email,TieuDe,NoiDung) values ('sadf','LG G3 Stylus (LGD690)','5.490.000 vnđ','sadf','01676331802','trantungvinacom@gmail.com','sadf','ádf');
delete from lienhe where Id=9;
delete from lienhe where Id=8;
delete from lienhe where Id=7;
